#' Analytical NIRA Intervention Analysis with Resampling-Based Inference
#'
#' @description
#' Implements the \emph{exact} (analytical) version of the NIRA intervention
#' analysis.  Instead of generating Monte Carlo samples with
#' \code{nodeIdentifyR::simulateResponses}, the mean number of activated nodes
#' is computed \strong{exactly} by enumerating all \eqn{2^p} activation
#' microstates of the Ising model (Cui et al., 2026).  The analytical solution
#' eliminates Monte Carlo error, so the only remaining source of uncertainty is
#' \strong{sampling error} — the network parameters are estimated from a finite
#' sample.  Accordingly, uncertainty is quantified by \strong{resampling the
#' original dataset} (not simulated samples) and re-computing the analytical
#' solution on each resampled network.
#'
#' Uncertainty is quantified by \strong{resampling the original dataset}
#' (rows resampled with replacement, the Ising network re-estimated, and the
#' exact solution re-computed on every resample).  A single resampling loop
#' simultaneously produces two tests, which answer different questions:
#' \describe{
#'   \item{\strong{Bootstrap test} (in \code{stat})}{Two-sided bootstrap
#'     \eqn{p}-value for \eqn{H_0: \Delta_i = 0} (the analytical analogue of
#'     the Monte-Carlo permutation test in \code{\link{permutationNIRAtest}}),
#'     standard errors, 95 \% percentile confidence intervals, and the
#'     proportion of resamples in which each node had the largest absolute
#'     intervention effect (\code{percenttop_1}, the analytical analogue of
#'     \code{\link{findMaxN}}).}
#'   \item{\strong{Random-target test} (in \code{random})}{The null is
#'     generated by \strong{permuting the assignment of the intervention
#'     across nodes}: within each resample the effect of node \eqn{i} is
#'     compared with the effects of the \eqn{p-1} other (randomly assigned)
#'     target nodes.  The \eqn{p}-value tests \eqn{H_0:} node \eqn{i} is
#'     \emph{not} a better intervention target than a randomly chosen node.
#'     It is reported \strong{without} multiple-comparison correction.
#'     Because the analytical solution makes every single-node effect
#'     deterministically non-zero, this ranking question (rather than
#'     \eqn{\Delta_i = 0}) is the meaningful one for target selection.}
#' }
#'
#' @param data A binary (0/1) \code{matrix} or \code{data.frame} of dimensions
#'   \eqn{n \times p} (\eqn{n} participants, \eqn{p} nodes).  Rows with missing
#'   values are removed with a warning.  Column names are used as node labels.
#' @param perturbation_type Character string specifying the direction of the
#'   intervention, matching \code{nodeIdentifyR::simulateResponses}:
#'   \code{"aggravating"} (threshold increased, node more likely to be 1) or
#'   \code{"alleviating"} (threshold decreased, node more likely to be 0).
#' @param edge_weights Optional symmetric \eqn{p \times p} numeric matrix of
#'   Ising edge weights (e.g., \code{fit$graph} from
#'   \code{bootnet::estimateNetwork}).  Must be supplied together with
#'   \code{thresholds}.  If \code{NULL}, both parameters are estimated from
#'   \code{data} with a fast saturated pseudo-likelihood estimator.
#' @param thresholds Optional numeric vector of length \eqn{p} of Ising
#'   threshold parameters (e.g., \code{fit$results$thresholds} from
#'   \code{bootnet::estimateNetwork}).  Must be supplied together with
#'   \code{edge_weights}.  If \code{NULL}, estimated from \code{data}.
#' @param amount_of_SDs_perturbation Positive numeric value specifying the
#'   magnitude of the perturbation in standard deviations of the threshold
#'   distribution.  Default: \code{2} (as in the NIRA tutorial).
#' @param nResample Non-negative integer.  Number of resamples of the original
#'   data used to quantify sampling uncertainty.  Default: \code{5000}.
#'   Set to \code{0} to skip resampling (exact results only; inference columns
#'   are \code{NA}).  Because each resample re-estimates the Ising network,
#'   large values are slow in serial mode; set \code{parallel = TRUE} for
#'   \code{nResample} \eqn{\geq 1000}.
#' @param method Multiple-comparison correction method passed to
#'   \code{\link[stats]{p.adjust}}: \code{"bonferroni"} (default),
#'   \code{"BH"}, \code{"holm"}, \code{"hochberg"}, \code{"hommel"},
#'   \code{"BY"}, \code{"fdr"}, or \code{"none"}.
#' @param seed Integer random seed for reproducibility.  Default: \code{2025}.
#'   Passed to \code{set.seed()} in serial mode and to
#'   \code{parallel::clusterSetRNGStream()} in parallel mode.
#' @param parallel Logical.  If \code{TRUE}, resamples are distributed across
#'   CPU cores.  Default: \code{FALSE}.
#' @param ncores Positive integer or \code{NULL}.  Number of CPU cores for
#'   parallel execution.  If \code{NULL} (default) and
#'   \code{parallel = TRUE}, uses \code{parallel::detectCores() - 1} cores.
#' @param resample_default Character string or \code{NULL} specifying the
#'   estimator used to re-estimate the Ising network on every bootstrap
#'   resample.  This controls which estimator the resampling CI/SE/p-values
#'   reflect.  Because the point estimate and the resampling must come from
#'   the \strong{same} estimator for the CI to be centred on the point
#'   estimate, the default is \code{NULL}, which matches the point estimate:
#'   \itemize{
#'     \item if \code{edge_weights} and \code{thresholds} are supplied
#'       (typically from \code{bootnet::estimateNetwork}), the resampling uses
#'       \code{bootnet::estimateNetwork(data, default = "IsingFit")};
#'     \item if the parameters are \code{NULL} (fast point estimate), the
#'       resampling uses the fast saturated pseudo-likelihood estimator.
#'   }
#'   Set \code{resample_default = "fast"} to force the fast estimator, or any
#'   \code{bootnet} \code{default} (e.g., \code{"IsingFit"}, \code{"mgm"}) to
#'   force a bootnet estimator.  \strong{Warning:} supplying \code{edge_weights}
#'   / \code{thresholds} from bootnet while resampling with \code{"fast"}
#'   mixes two estimators and makes the CI poorly centred on the point
#'   estimate; this is why the default is \code{NULL}.
#'
#' @return
#' A named \code{list} with the following elements:
#' \describe{
#'   \item{\code{stat}}{A \code{data.frame} with one row per intervention node
#'     (rows named by node label) and columns:
#'     \describe{
#'       \item{\code{mean_activation}}{Exact mean number of activated nodes
#'         after the intervention.}
#'       \item{\code{ci_lower}, \code{ci_upper}}{Percentile 95 \% CI of the
#'         resampled mean activation.}
#'       \item{\code{effect}}{Intervention effect
#'         \eqn{\Delta_i = \mathrm{MA}_i - \mathrm{MA}_0} (exact).}
#'       \item{\code{cohen_d}}{Standardised effect
#'         \eqn{\Delta_i / \mathrm{SD}(\mathrm{MA}_0)}, using the exact
#'         standard deviation of the original activation distribution.}
#'       \item{\code{se_effect}, \code{ci_effect_lower},
#'         \code{ci_effect_upper}}{Standard error and percentile 95 \% CI of
#'         \eqn{\Delta_i} across resamples.}
#'       \item{\code{p}}{Two-sided bootstrap \eqn{p}-value for
#'         \eqn{H_0: \Delta_i = 0}.}
#'       \item{\code{p.adjust}}{Adjusted bootstrap \eqn{p}-value.}
#'       \item{\code{percenttop_1}}{Proportion of resamples in which the node
#'         had the largest absolute intervention effect (analytical stability
#'         metric, analogue of \code{\link{findMaxN}}).}
#'     }
#'   }
#'   \item{\code{random}}{A \code{data.frame} with the one-sided
#'     \eqn{p}-value for each node, testing \eqn{H_0:} node \eqn{i} is not a
#'     better intervention target than a randomly chosen node.  Reported
#'     \strong{uncorrected} (no multiple-comparison adjustment).  Columns:
#'     \code{node}, \code{effect}, \code{p}.}
#'   \item{\code{exact}}{A \code{data.frame} with the exact mean activation of
#'     the \code{"original"} network and of each one-node intervention.}
#'   \item{\code{resample_effects}}{A numeric \code{matrix} of dimensions
#'     \code{B} \eqn{\times} \eqn{p} holding the resampled intervention
#'     effects; \code{NULL} when \code{nResample = 0}.}
#'   \item{\code{plot}}{A \code{\link[ggplot2]{ggplot}} object showing the
#'     exact mean activation of each condition with 95 \% CI error bars and
#'     significance stars derived from \code{p.adjust}.  Save with
#'     \code{ggplot2::ggsave()}.}
#'   \item{\code{parameters}}{A named \code{list} recording the thresholds,
#'     edge weights, perturbation definition and resampling settings used.}
#' }
#'
#' @section Method notes:
#' \itemize{
#'   \item The exact computation transforms the \eqn{\{0,1\}}-coded Ising
#'     parameters into the spin (\eqn{\pm 1}) convention and enumerates all
#'     \eqn{2^p} microstates \strong{once per network} with a numerically
#'     stable log-sum-exp scheme.  A one-node intervention changes only the
#'     single-node field, so the perturbed mean activation is obtained by
#'     exactly reweighting the microstates by \eqn{e^{\Delta_i v_i}} — no
#'     re-enumeration of the \eqn{2^p} states is needed for the \eqn{p}
#'     interventions.  The result is identical to
#'     \code{Isinglandr::make_2d_Isingland(transform = TRUE)}.
#'   \item The intervention magnitude is fixed at
#'     \code{amount_of_SDs_perturbation} \eqn{\times} \code{sd(thresholds)}
#'     (the point-estimate SD) across all resamples, so the resampled effects
#'     reflect sampling error in the network structure only.
#'   \item The resampling loop re-estimates the network with a saturated
#'     nodewise logistic-regression (pseudo-likelihood) estimator, which is
#'     substantially faster than \code{bootnet::estimateNetwork} but performs
#'     no model selection.  For the point estimate, either provide parameters
#'     from your preferred estimator (e.g., \code{bootnet}) or accept the
#'     default fast estimator.
#' }
#'
#' @examples
#' ## Example 1: exact analysis + bootstrap inference (fast demo)
#' \dontrun{
#' data("single_gds", package = "NIRApost")
#'
#' res <- analyticalNIRAtest(
#'   data              = single_gds,
#'   perturbation_type = "aggravating",
#'   nResample         = 100,   # 5000 recommended for publication
#'   seed              = 2025
#' )
#' res$stat
#' res$plot
#' }
#'
#' ## Example 2: reproduce the paper's exact Fig. 5 point estimates by
#' ## supplying the bootnet IsingFit parameters; both bootstrap and
#' ## permutation results are returned together
#' \dontrun{
#' fit <- bootnet::estimateNetwork(single_gds, default = "IsingFit",
#'                                 rule = "AND")
#' res <- analyticalNIRAtest(
#'   data              = single_gds,
#'   edge_weights      = fit$results$weiadj,
#'   thresholds        = fit$results$thresholds,
#'   perturbation_type = "aggravating",
#'   nResample         = 5000,
#'   parallel          = TRUE
#' )
#' head(res$stat)        # bootstrap-based inference (SE, CI, p, percenttop_1)
#' res$random            # target-vs-random p-values (uncorrected)
#' }
#'
#' ## Example 3: exact-only (no resampling)
#' \dontrun{
#' res0 <- analyticalNIRAtest(single_gds, "aggravating", nResample = 0)
#' res0$exact
#' }
#'
#' @author
#' Fei Wang \email{bjnwangfei0501@@outlook.com}
#'
#' @seealso
#' \itemize{
#'   \item \code{\link{permutationNIRAtest}} — Monte-Carlo-based permutation
#'     test (simulated samples).
#'   \item \code{\link{stabilityNIRAtest}} / \code{\link{findMaxN}} —
#'     Monte-Carlo-based stability assessment.
#'   \item \code{\link[Isinglandr]{make_2d_Isingland}} — the exact
#'     enumeration engine whose output this function reproduces.
#' }
#'
#' @export
analyticalNIRAtest <- function(data,
                               perturbation_type = c("aggravating",
                                                     "alleviating"),
                               edge_weights = NULL,
                               thresholds = NULL,
                               amount_of_SDs_perturbation = 2,
                               nResample = 5000,
                               method = "bonferroni",
                               seed = 2025,
                               parallel = FALSE,
                               ncores = NULL,
                               resample_default = NULL) {

  # ------------------------------ arguments ------------------------------
  perturbation_type <- match.arg(perturbation_type)

  if (!is.matrix(data) && !is.data.frame(data))
    stop("'data' must be a binary matrix or data frame.")
  data <- as.matrix(data)
  if (anyNA(data)) {
    keep <- stats::complete.cases(data)
    warning(sum(!keep), " row(s) with missing values removed.")
    data <- data[keep, , drop = FALSE]
  }
  if (!all(data %in% c(0, 1)))
    stop("'data' must contain only binary entries (0/1).")
  if (nrow(data) < 3 || ncol(data) < 2)
    stop("'data' must contain at least 3 rows and 2 columns.")
  if (!is.null(seed) && (!is.numeric(seed) || length(seed) != 1))
    stop("'seed' must be a single number or NULL.")

  p <- ncol(data)
  if (is.null(colnames(data))) colnames(data) <- paste0("V", seq_len(p))
  node_names <- colnames(data)

  if (2^p > 2^20)
    warning("2^p = ", 2^p, " microstates; exact enumeration may be slow for p > 20.")

  if (xor(is.null(thresholds), is.null(edge_weights)))
    stop("Supply BOTH 'thresholds' and 'edge_weights', or neither.")

  valid_m <- c("holm", "hochberg", "hommel", "bonferroni", "BH",
               "BY", "fdr", "none")
  if (!method %in% valid_m)
    stop("Invalid method. Choose from: ", paste(valid_m, collapse = ", "))
  if (!is.numeric(nResample) || length(nResample) != 1 || nResample < 0 ||
      nResample != floor(nResample))
    stop("'nResample' must be a single non-negative integer.")
  nResample <- as.integer(nResample)

  # Determine the resampling estimator.  Default (NULL) matches the point
  # estimate: supplied parameters -> bootnet; else fast.  "fast" forces the
  # fast estimator; any bootnet 'default' name forces that bootnet estimator.
  use_bootnet <- TRUE
  if (is.null(resample_default)) {
    use_bootnet <- !is.null(thresholds)
  } else if (identical(resample_default, "fast")) {
    use_bootnet <- FALSE
  } else {
    if (!is.character(resample_default) || length(resample_default) != 1)
      stop("'resample_default' must be 'fast', a bootnet 'default' name, or NULL.")
    if (!requireNamespace("bootnet", quietly = TRUE))
      stop("'resample_default' requires the 'bootnet' package to be installed.")
    use_bootnet <- TRUE
  }
  if (use_bootnet) {
    if (!requireNamespace("bootnet", quietly = TRUE))
      stop("Resampling with bootnet requires the 'bootnet' package to be installed. ",
           "Install it, or set resample_default = 'fast'.")
    # The resampling must use the same bootnet estimator as the point
    # estimate.  When the point-estimate parameters came from
    # bootnet::estimateNetwork(default = "IsingFit") (the typical workflow),
    # default to the same estimator.
    if (is.null(resample_default)) resample_default <- "IsingFit"
  }

  # ------------------------ exact analytical engine ------------------------
  # Returns the exact mean (and SD) of the number of active nodes for a {0,1}
  # Ising model, for the original network and for each one-node threshold
  # perturbation.  The 2^p microstates are enumerated ONCE per network (spin
  # coding, stable log-sum-exp).  A perturbation of node i changes only the
  # single-node field, so the perturbed weights are obtained by exactly
  # reweighting the microstates by exp(delta_spin[i] * v_i): no re-enumeration
  # and no re-computation of the Hamiltonian for the p interventions.
  # Equivalent to Isinglandr::make_2d_Isingland(transform = TRUE).
  analytical_all_means <- function(thr, W, delta_spin) {
    m  <- 0.5 * thr + 0.25 * (W %*% rep(1, length(thr)))  # spin thresholds
    Ws <- 0.25 * W                                        # spin weights
    S <- as.matrix(expand.grid(rep(list(c(-1, 1)), length(thr))))
    h  <- -0.5 * rowSums((S %*% Ws) * S) - S %*% m        # Hamiltonian H(v)
    lf <- -h                                              # log P(v) = -H(v)
    lf <- lf - max(lf)                                    # log-sum-exp
    f       <- exp(lf)
    n_active <- (rowSums(S) + length(thr)) / 2
    Z       <- sum(f)
    ma0     <- sum(n_active * f) / Z
    m2      <- sum(n_active^2 * f) / Z
    sd0     <- sqrt(max(m2 - ma0^2, 0))
    ma_i    <- numeric(length(thr))
    for (i in seq_along(thr)) {
      w       <- exp(delta_spin[i] * S[, i])
      ma_i[i] <- sum(n_active * f * w) / sum(f * w)
    }
    list(mean_original = ma0, sd_original = sd0, mean_nodes = ma_i)
  }

  # Saturated nodewise logistic regression (pseudo-likelihood) estimator,
  # roughly 25x faster than bootnet::estimateNetwork.  Used for the
  # point estimate when parameters are not supplied and inside the
  # resampling loop.
  estimate_ising_fast <- function(X) {
    pn   <- ncol(X)
    thr  <- numeric(pn)
    W    <- matrix(0, pn, pn)
    for (j in seq_len(pn)) {
      others <- seq_len(pn)[-j]
      g <- stats::glm.fit(x = cbind(1, X[, others, drop = FALSE]),
                          y = X[, j],
                          family = stats::binomial())
      thr[j]   <- g$coefficients[1]
      W[j, others] <- g$coefficients[-1]
    }
    W <- (W + t(W)) / 2
    list(graph = W, thresholds = thr)
  }

  # --------------------------- point estimates ---------------------------
  if (is.null(thresholds)) {
    est         <- estimate_ising_fast(data)
    thresholds  <- est$thresholds
    edge_weights <- est$graph
  } else {
    thresholds   <- as.numeric(thresholds)
    edge_weights <- as.matrix(edge_weights)
    if (length(thresholds) != p)
      stop("'thresholds' must have length p = ", p, ".")
    if (!all(dim(edge_weights) == c(p, p)))
      stop("'edge_weights' must be a ", p, " x ", p, " matrix.")
    if (any(diag(edge_weights) != 0))
      warning("Diagonal of 'edge_weights' set to 0.")
    diag(edge_weights) <- 0
  }

  sdt <- stats::sd(thresholds)
  if (is.finite(sdt) && sdt > 0) {
    delta <- amount_of_SDs_perturbation * sdt
  } else {
    warning("sd(thresholds) == 0; a raw perturbation of ",
            amount_of_SDs_perturbation, " is applied instead.")
    delta <- amount_of_SDs_perturbation
  }
  sgn <- if (perturbation_type == "aggravating") 1 else -1
  # Spin-convention threshold change per node (0.5 * {0,1}-coding change).
  delta_spin <- rep(sgn * 0.5 * delta, p)

  o            <- analytical_all_means(thresholds, edge_weights, delta_spin)
  ma_original  <- o$mean_original
  sd_original  <- o$sd_original
  ma_nodes     <- o$mean_nodes
  effects      <- ma_nodes - ma_original

  # ------------------------------ resampling ------------------------------
  resample_means <- NULL
  if (nResample > 0) {

    one_rep <- function(b) {
      attempt <- 0L
      ok <- FALSE
      repeat {
        attempt <- attempt + 1L
        Xr <- data[sample.int(nrow(data), replace = TRUE), , drop = FALSE]
        if (use_bootnet) {
          e <- tryCatch({
            bfit <- bootnet::estimateNetwork(Xr, default = resample_default)
            list(thresholds = as.numeric(bfit$intercepts),
                 graph      = bfit$graph)
          }, error = function(err) NULL)
        } else {
          e <- tryCatch(estimate_ising_fast(Xr), error = function(err) NULL)
        }
        ok <- !is.null(e) &&
              all(is.finite(e$thresholds)) &&
              all(is.finite(e$graph))
        if (ok || attempt >= 20L) break
      }
      if (!ok) return(c(original = NA_real_, rep(NA_real_, p)))
      oo <- analytical_all_means(e$thresholds, e$graph, delta_spin)
      c(original = oo$mean_original, oo$mean_nodes)
    }

    if (parallel) {
      if (is.null(ncores)) ncores <- max(1L, parallel::detectCores() - 1L)
      cl <- parallel::makeCluster(ncores)
      on.exit(parallel::stopCluster(cl), add = TRUE)
      parallel::clusterSetRNGStream(cl, seed)
      parallel::clusterExport(
        cl,
        varlist = c("data", "delta_spin", "p",
                    "use_bootnet", "resample_default",
                    "estimate_ising_fast", "analytical_all_means",
                    "one_rep"),
        envir   = environment())
      if (use_bootnet)
        parallel::clusterEvalQ(cl, requireNamespace("bootnet", quietly = TRUE))
      out <- parallel::parLapply(cl, seq_len(nResample), one_rep)
    } else {
      if (!is.null(seed)) set.seed(seed)
      out <- lapply(seq_len(nResample), one_rep)
    }

    resample_means <- do.call(rbind, out)
    if (anyNA(resample_means)) {
      keep <- stats::complete.cases(resample_means)
      dropped <- sum(!keep)
      if (dropped == nResample)
        stop("All resamples failed network estimation.")
      if (dropped > 0)
        warning(dropped, " resample(s) failed network estimation and were dropped.")
      resample_means <- resample_means[keep, , drop = FALSE]
    }
    colnames(resample_means) <- c("original", node_names)
  }

  # ------------------------------ statistics ------------------------------
  if (is.null(resample_means)) {
    se_effect  <- ci_effect_lower <- ci_effect_upper <- rep(NA_real_, p)
    ci_lower   <- ci_upper <- rep(NA_real_, p)
    pvals      <- rep(NA_real_, p)
    p_perm     <- rep(NA_real_, p)
    percenttop <- rep(NA_real_, p)
    names(ci_lower) <- names(ci_upper) <- node_names
  } else {
    B                <- nrow(resample_means)
    resample_effects <- resample_means[, -1, drop = FALSE] -
                        resample_means[, "original"]
    colnames(resample_effects) <- node_names

    se_effect       <- apply(resample_effects, 2, stats::sd, na.rm = TRUE)
    ci_effect_lower <- apply(resample_effects, 2, stats::quantile,
                             probs = 0.025, na.rm = TRUE)
    ci_effect_upper <- apply(resample_effects, 2, stats::quantile,
                             probs = 0.975, na.rm = TRUE)
    ci_lower        <- apply(resample_means, 2, stats::quantile,
                             probs = 0.025, na.rm = TRUE)
    ci_upper        <- apply(resample_means, 2, stats::quantile,
                             probs = 0.975, na.rm = TRUE)

    # Ranking stability: proportion of resamples in which each node had the
    # largest absolute intervention effect (analytical analogue of findMaxN).
    top1 <- apply(abs(resample_effects), 1, which.max)
    percenttop <- tabulate(top1, nbins = p) / B

    # Bootstrap test for H0: effect = 0, centred on the observed estimate so
    # the null is centred at zero.  With the analytical solution these
    # p-values are typically very small for every node; the discriminating
    # outputs are percenttop_1, the effect CIs, and the permutation test.
    pvals <- sapply(seq_len(p), function(i) {
      d <- resample_effects[, i]
      (1 + sum(abs(d - effects[i]) >= abs(effects[i]))) / (B + 1)
    })

    # Random-target test: H0 = node i is not a better target than a randomly
    # chosen node.  Within each resample, the (signed) effect of node i is
    # compared with the effects of the p-1 other nodes of that SAME resample
    # (a within-resample permutation of the target assignment); the p-value is
    # the proportion of those paired comparisons in which another node's
    # effect is at least as strong.  'sgn' aligns "better" with the
    # hypothesised direction (positive for aggravating, negative for
    # alleviating).  Using the resampled effects for both the observation and
    # the comparison pool keeps them on the same scale (the point estimate is
    # NOT used here).  Reported uncorrected in the $random element.
    Z  <- sgn * resample_effects
    p_perm <- sapply(seq_len(p), function(i) {
      obs    <- Z[, i]
      others <- Z[, -i, drop = FALSE]
      (1 + sum(others >= obs)) / (B * (p - 1) + 1)
    })
  }

  stat <- data.frame(
    node             = node_names,
    mean_activation  = ma_nodes,
    ci_lower         = unname(ci_lower[node_names]),
    ci_upper         = unname(ci_upper[node_names]),
    effect           = effects,
    cohen_d          = effects / sd_original,
    se_effect        = se_effect,
    ci_effect_lower  = ci_effect_lower,
    ci_effect_upper  = ci_effect_upper,
    p                = pvals,
    p.adjust         = stats::p.adjust(pvals, method = method),
    percenttop_1     = percenttop,
    row.names        = node_names,
    stringsAsFactors = FALSE
  )
  stat$stars <- ifelse(is.na(stat$p.adjust), "",
                       ifelse(stat$p.adjust < 0.001, "***",
                              ifelse(stat$p.adjust < 0.01, "**",
                                     ifelse(stat$p.adjust < 0.05, "*", ""))))

  exact <- data.frame(
    condition       = c("original", node_names),
    mean_activation = c(ma_original, ma_nodes),
    stringsAsFactors = FALSE
  )

  # -------------------------------- plot ---------------------------------
  plot_data <- data.frame(
    condition       = c("original", node_names),
    mean_activation = c(ma_original, ma_nodes),
    ci_lower        = unname(c(ci_lower["original"], ci_lower[node_names])),
    ci_upper        = unname(c(ci_upper["original"], ci_upper[node_names])),
    stars           = c("", stat$stars),
    stringsAsFactors = FALSE
  )
  if (perturbation_type == "aggravating") {
    ord <- order(plot_data$condition != "original",
                 -plot_data$mean_activation)
  } else {
    ord <- order(plot_data$condition != "original",
                 plot_data$mean_activation)
  }
  plot_data <- plot_data[ord, , drop = FALSE]
  plot_data$id <- seq_len(nrow(plot_data)) - 1

  gp <- ggplot2::ggplot(
          plot_data, ggplot2::aes(x = id, y = mean_activation, group = 1)) +
    ggplot2::geom_line(color = "steelblue", linewidth = 1) +
    ggplot2::geom_point(size = 3, color = "tomato") +
    ggplot2::geom_errorbar(
      ggplot2::aes(ymin = ci_lower, ymax = ci_upper),
      width = 0.2, color = "gray40") +
    ggplot2::scale_x_continuous(breaks = plot_data$id,
                                labels = plot_data$condition) +
    ggplot2::labs(x = "Condition", y = "Mean activation (exact)", title = "") +
    ggplot2::theme_minimal() +
    ggplot2::theme(
      axis.title.x       = ggplot2::element_text(face = "bold", size = 12),
      axis.title.y       = ggplot2::element_text(face = "bold", size = 12),
      axis.text.x        = ggplot2::element_text(angle = 45, hjust = 1,
                                                 face = "bold", size = 10),
      axis.text.y        = ggplot2::element_text(face = "bold", size = 10),
      panel.grid.major.x = ggplot2::element_blank())
  if (any(nzchar(plot_data$stars)))
    gp <- gp + ggplot2::geom_text(
      ggplot2::aes(label = stars, y = mean_activation + 1.2 *
                     (mean_activation - ci_lower)),
      color = "black", size = 5, vjust = 0.5)

  random <- data.frame(
    node  = node_names,
    effect = effects,
    p      = p_perm,
    row.names = node_names,
    stringsAsFactors = FALSE
  )

  list(
    stat              = stat,
    random            = random,
    exact             = exact,
    resample_effects  = if (is.null(resample_means)) NULL
                        else resample_means[, -1, drop = FALSE],
    plot              = gp,
    parameters        = list(
      perturbation_type            = perturbation_type,
      amount_of_SDs_perturbation   = amount_of_SDs_perturbation,
      delta                        = delta,
      nResample                    = if (is.null(resample_means)) 0
                                     else nrow(resample_means),
      method                       = method,
      seed                         = seed,
      resample_default             = if (use_bootnet) resample_default
                                     else "fast",
      thresholds                   = thresholds,
      edge_weights                 = edge_weights
    )
  )
}
